# 1. Stage para dependências
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci

# 2. Imagem final (dev)
FROM node:20-alpine
WORKDIR /app

# libs extras 
RUN apk add --no-cache bash postgresql-client


COPY --from=deps /app/node_modules ./node_modules

# copia resto do projeto
COPY . .

# deixa scripts executáveis
RUN chmod +x start.sh

EXPOSE 3000

# ENTRYPOINT roda só uma vez, ANTES do CMD
ENTRYPOINT ["sh", "./start.sh"]
