# 1. Stage para dependências
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci

# 2. Imagem final (dev)
FROM node:20-alpine
WORKDIR /app

ENV NODE_ENV=production

RUN apk add --no-cache bash postgresql-client

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN chmod +x start.sh

EXPOSE 3001

ENTRYPOINT ["sh", "./start.sh"]
